jwt:
  private-key-path: classpath:keys/private.pem
  public-key-path: classpath:keys/public.pem

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8000

spring:
  application:
      name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-service
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngoquanghuy0310@gmail.com
    password: tychlmxomtkudyap
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
