eureka:
  instance:
    hostname: media_service
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 8800

spring:
  application:
    name: media_service
  datasource:
    url: jdbc:postgresql://postgres:5432/media_service
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
